steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    entrypoint: "bash"
    args:
      - "-c"
      - |
        gcloud functions deploy $_FUNCTION_NAME \
          --runtime nodejs18 \
          --trigger-http \
          --entry-point $_ENTRY_POINT \
          --set-env-vars "BUCKET_NAME=test-taking-bucket,IMAGE_BASE_URL=https://storage.googleapis.com/<BUCKET_NAME>/<FILE_NAME>,JWT_EXPIRES_IN=1d,NODE_ENV=production,ORIGIN_URL_FOR_TESTS=https://test-taking.netlify.app,SALT_COST_FACTOR=10" \
          --set-secrets "DB_USERNAME=projects/$_PROJECT_ID/secrets/DB_USERNAME:latest,PASSWORD=projects/$_PROJECT_ID/secrets/PASSWORD:latest,DATABASE_TEST_TAKING=projects/$_PROJECT_ID/secrets/DATABASE_TEST_TAKING:latest,JWT_SECRET_FOR_TESTS=projects/$_PROJECT_ID/secrets/JWT_SECRET_FOR_TESTS:latest" \
          --region $_REGION

substitutions:
  _PROJECT_ID: "allprojects-424621"
  _REGION: "us-central1"
  _FUNCTION_NAME: "spellings-function"
  _ENTRY_POINT: "spellingsApi"

timeout: "600s"
